name: Mod CLI JAR IT
on: [workflow_call, workflow_dispatch]
jobs:
  run-test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      matrix:
        cli_version: [ 'staging', 'stable' ]
        recipe_version: [ 'LATEST', 'RELEASE' ]
      max-parallel: 1
    steps:
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Clone Spring Pet Clinic Repository
        uses: actions/checkout@v2
        with:
          repository: 'openrewrite/spring-petclinic-migration'
          ref: '2.1.x'
          path: 'spring-petclinic-migration'
      - name: Download ModCLI Staging
        run: |
          mkdir modcli
          curl --request GET \
            --output modcli/mod.tar.gz \
            --url 'https://api.app.moderne.io/cli/download?operatingSystem=linux-tar&environment=${{ matrix.cli_version }}' \
            --header 'Authorization: ${{ secrets.MODERNE_SAAS_ACCESS_TOKEN }}'
      - name: Setup ModCLI
        uses: developerdino/action-tar@v1
          with:
            args: tar -xzf modcli/mod.tar.gz -C modcli
      - name: Activate ModCLI
        run: modcli/mod config moderne edit https://app.moderne.io --token ${{ secrets.MODERNE_SAAS_ACCESS_TOKEN }}
      - name: Load Recipes
        run: modcli/mod config recipes jar install org.openrewrite.recipe:rewrite-spring:${{ matrix.recipe_version }}
      - name: Build LST
        run: modcli/mod build ./spring-petclinic-migration
      - name: Update Spring Boot with OpenRewrite latest versions
        run: modcli/mod run ./spring-petclinic-migration --recipe org.openrewrite.java.spring.boot3.UpgradeSpringBoot_3_3