name: Integration Tests
on: workflow_dispatch
jobs:
  Gradle Plugin:
    uses: .github/workflows/integration-test-mvn.yml@main
  Maven Plugin:
    uses: .github/workflows/integration-test-gradle.yml@main
  Mod CLI JAR:
    uses: .github/workflows/integration-test-modcli-jar.yml@main