name: Integration Tests
on: workflow_dispatch
jobs:
  Gradle Plugin:
    uses: ./integration-test-mvn.yml@main
  Maven Plugin:
    uses: ./integration-test-gradle.yml@main
  Mod CLI JAR:
    uses: ./integration-test-modcli-jar.yml@main